### ISSUE TITLE
HTTP 400 (api_error:)

### ISSUE THREAD

**Issue by NoMansPC** [suncloudsmoon/TextCraft#2]
Gives me the following error:

"all-minilm:latest" does not support chat

I've installed all-minilm. I suspect this may also be part of the reason why I can't connect ollama to another word add-in I was trying before finding this one.

**Comment by suncloudsmoon** [comment]
What models do you have installed in ollama? You can get a list of the installed models by typing `ollama ls` in the command line. `all-minilm:latest` is an embedding model that is used for RAG instead of chat. I believe you need to install a chat model like `qwen2.5:1.5b`. Correct me if I'm wrong.

**Comment by NoMansPC** [comment]
> What models do you have installed in Ollama? You can get a list of the installed models by typing `ollama ls` in the command line. `all-minilm:latest` is an embedding model that is used for RAG instead of chat. I believe you need to install a chat model like `qwen2.5:1.5b`. Correct me if I'm wrong.

I have rocinante-12b-v1.1 installed. Currently, it works with OpenWebUI. I'm a bit of an Ollama noob. I run CMD, then the command to load the model, and then I load Word with your add-in. What am I doing wrong?

**Comment by suncloudsmoon** [comment]
Typically, when the user installs Ollama on their desktop, they don't need to load any models at any time. Ollama takes care of it automatically. Additionally, Ollama is also in the `Task Manager-> Startup apps` so Ollama automatically starts up when you sign in. Is Ollama installed on your desktop or inside OpenWebUI? If `ollama ls` lists both `rocinante-12b-v1.1` and `all-minilm:latest` together, you should see no issues. This is how my `ollama ls` looks like:

![image](https://github.com/user-attachments/assets/8ae83530-8092-41b9-86e0-e0bb5d33f9e2)

**Comment by NoMansPC** [comment]
I tried again without following the procedure I was using before and it still doesn't work. The CMD window, after using the ollama ls command, lists all-minilm:latest and rocinante-12b-v1.1, but I still get the same HTTP 400 error.

**Comment by NoMansPC** [comment]
Only when I click on Generate. The model (Rocinante) even shows up on the list in the add-in. I think it's a problem inherent with my Word installation, but I have no idea how to start to fix it. As I said, I also couldn't get Ollama to connect with another add-in even though it works fine with Openwebui.

**Comment by NoMansPC** [comment]
Actually, nevermind lol I had to quit Ollama on my taskbar (the little icon) and then run ollama serve in CMD. Now the add-in works.

**Comment by suncloudsmoon** [comment]
I'm glad you found a fix! It turns out that there was a [small bug in the ThisAddIn.cs file that chose the first model in the list instead of the first language model](https://github.com/suncloudsmoon/TextCraft/blob/6bc9f5622738e1ea87d129af91dc4aee05ddb7c9/ThisAddIn.cs#L242). I completely overlooked this bug and It came to my attention thanks to this issue. Thanks for bringing up this issue. It should be fixed in version 1.0.8, which was just released right now. So, you can use the add-in (hopefully) without typing `ollama serve` each time.
